In [3]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel() # num of elements

12

In [9]:
X = x.reshape(3,4) # 改变形状
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.zeros((2,3,4))  # 形状是2，3，4

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.tensor([[1,2,3,4], [3,4,5,6],[4,5,6,7]])  # tensor??

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6],
        [4, 5, 6, 7]])

In [15]:
torch.tensor([[1,2,3,4], [3,4,5,6],[4,5,6,7]]).shape # tensor??

torch.Size([3, 4])

In [16]:
# 加减乘除
x = torch.tensor([1.0, 2,3,4])
y = torch.tensor([2,3,3,4])
x+y, x-y, x*y,x/y, x**y

(tensor([3., 5., 6., 8.]),
 tensor([-1., -1.,  0.,  0.]),
 tensor([ 2.,  6.,  9., 16.]),
 tensor([0.5000, 0.6667, 1.0000, 1.0000]),
 tensor([  1.,   8.,  27., 256.]))

In [40]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))

In [41]:
Y = torch.tensor([[1.0,2,3,4], [3,4,5,6],[4,5,6,7]])

In [21]:
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1) # 0 行 堆叠  1 列堆叠

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 3.,  4.,  5.,  6.],
         [ 4.,  5.,  6.,  7.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  3.,  4.,  5.,  6.],
         [ 8.,  9., 10., 11.,  4.,  5.,  6.,  7.]]))

In [25]:
# 逻辑运算符
X==Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
# sum 
X.sum()  # 变成一个元素的标量

tensor(66.)

## 广播机制

In [30]:
#广播机制
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [28]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [33]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
# 元素的访问
X[-1], X[1:3] # 第一行到第二行 还有0行

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [35]:
X[1,2] = 100
X

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 100.,   7.],
        [  8.,   9.,  10.,  11.]])

In [37]:
X[0:2, :] = 200
X

tensor([[200., 200., 200., 200.],
        [200., 200., 200., 200.],
        [  8.,   9.,  10.,  11.]])

In [38]:
before = id(Y) # 类似指针
Y = Y + X
id(Y) == before # 运行一些操作可能会导致新结果分配内存

False

In [42]:
id(Y)

140193133806000

In [44]:
Y = Y + X
id(Y)

140193133806000

In [46]:
#执行原地操作
Z= torch.zeros_like(Y)
print('id_z:', id(Z))
Z[:] = X + Y
print('id_z:', id(Z))

id_z: 140193122290496
id_z: 140193122290496


In [47]:
before = id(X) # 类似指针
X += Y
id(X) == before # 运行一些操作可能会导致新结果分配内存

True

In [48]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)
# 转换numpy 张量

(numpy.ndarray, torch.Tensor)

In [50]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)