In [1]:
import torch

In [2]:
x = torch.tensor([3.0])

In [3]:
y = torch.tensor([2.0])

In [5]:
x = torch.arange(4)

In [7]:
x[3]

tensor(3)

In [8]:
len(x)

4

In [9]:
x.shape

torch.Size([4])

In [10]:
A= torch.arange(20).reshape(5,4)

In [11]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [13]:
A.T # 转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [15]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

In [18]:
B # 对称

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [19]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [20]:
X = torch.arange(24).reshape(2,3,4)

In [22]:
X # 第一维度是 层，第二维度是行， 第三维度 是列

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [23]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [24]:
B = A.clone() # 通过分配新内存，将A的一个副本分配给B

In [25]:
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [27]:
A * B # 哈达马积分

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [28]:
a = 2
X = torch.arange(24).reshape(2,3,4)

In [29]:
a+X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [30]:
x = torch.arange(4, dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [44]:
A = torch.arange(20*2, dtype=torch.float32).reshape(2,5,4)
A.shape, A.sum() # 全部求和
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [38]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [39]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [40]:
A.sum(axis=[0,1])

tensor([180, 190, 200, 210])

In [41]:
A.sum()

tensor(780)

In [45]:
A.mean()

tensor(19.5000)

In [46]:
A.sum()/A.numel() # number elements

tensor(19.5000)

In [48]:
A.mean(axis=0)

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])

In [49]:
A.sum(axis=0)/A.shape[0]

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])

In [63]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
print(A)
sum_A = A.sum(axis=1, keepdims=True) # 列 行
sum_A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [62]:
A/sum_A  # 通过广播将A除以sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [57]:
sum_A = A.sum(axis=1) # 层 行 列
sum_A # 这样轴数改变

tensor([ 6., 22., 38., 54., 70.])

In [64]:
A.cumsum(axis=0) # 某个轴计算A元素的累积综合，0就是 列

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [65]:
A.cumsum(axis=1) # 某个轴计算A元素的累积综合

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

In [67]:
sum_A = A.sum(axis=0, keepdims=True)
sum_A# 层 行 列

tensor([[40., 45., 50., 55.]])

In [68]:
sum_A = A.sum(axis=0)
sum_A# 层 行 列

tensor([40., 45., 50., 55.])

In [69]:
y = torch.ones(4, dtype=torch.float32)
x,y,torch.dot(x,y) # 点积

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [70]:
torch.sum(x*y)

tensor(6.)

In [71]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [74]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [76]:

B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

# 范数

In [77]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # 3,4 -> 5

tensor(5.)

In [78]:
torch.abs(u).sum() # l1范数

tensor(7.)

In [79]:
torch.norm(torch.ones((4,9))) # 弗洛尼乌斯范数，矩阵平防和的平方根

tensor(6.)

In [80]:
torch.ones((4,9))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])