y = 2XTX, 关于X求导

In [7]:
import torch 

In [9]:
x = torch.arange(4.0)

In [10]:
x

tensor([0., 1., 2., 3.])

In [11]:
x.requires_grad_(True) # 等价于 x = torch.arange(4.0, requrie_grad=True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [12]:
x.grad

In [13]:
y = 2 * torch.dot(x,x)

In [14]:
y # 正向计算

tensor(28., grad_fn=<MulBackward0>)

grad_fn 属性保存了创建当前张量的函数的引用。这些函数可以是加法、乘法、卷积等基本操作，也可以是用户自定义的操作或模型的参数更新操作。grad_fn 属性构成了一个计算图，每个节点都是一个梯度函数，用于计算当前张量相对于计算图中其他张量的梯度。mul表示乘法操作，此外还有sumbackward0等加法

In [15]:
y.backward()

In [16]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [17]:
x.grad == 4 * x

tensor([True, True, True, True])

In [18]:
# 在默认情况下，Pytorch会累积梯度，我们需要清楚之前的值
x.grad.zero_() # 梯度清零的意思！

tensor([0., 0., 0., 0.])

In [19]:
y = sum(x)
y.backward() # 可以理解，求和导数为1

In [20]:
x.grad

tensor([1., 1., 1., 1.])

In [21]:
x.grad.zero_() # 梯度清零的意思！

tensor([0., 0., 0., 0.])

In [22]:
y = x*x # backward 就是个矩阵，很少对一个向量导数求导，一般都是对标量求导
y.sum().backward()

In [23]:
x.grad

tensor([0., 2., 4., 6.])

In [24]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u*x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [25]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [27]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b *2
    if b.sum()> 0:
        c = b
    else:
        c = 100*b
    return c

a = torch.randn(size=(), requires_grad =True)
d = f(a)
d.backward()

a.grad == d/a  # 不管怎么算都是 k * a，所以 k * a/a = k 就是系数

tensor(False)