In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4,8))

In [4]:
Y.mean()

tensor(-7.4506e-09, grad_fn=<MeanBackward0>)

# 带参数的层

In [9]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
    
layer = MyLinear(5,3)
layer.weight

Parameter containing:
tensor([[ 0.8024,  0.1307,  0.3713],
        [ 0.6996,  0.2987,  0.4433],
        [ 1.1128,  2.2160,  0.2270],
        [-2.4606, -0.1465,  1.2340],
        [ 1.5799,  1.6797,  0.6218]], requires_grad=True)

In [10]:
layer(torch.rand(2,5))

tensor([[0.0000, 1.0739, 1.1206],
        [0.3036, 2.0601, 1.1682]])

In [12]:
net =nn.Sequential(MyLinear(64, 8), MyLinear(8,1))
net(torch.rand(2,64))

tensor([[0.3008],
        [2.4881]])