In [2]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)

In [3]:
torch.save(x, 'x-file') # 当前目录存储

In [4]:
x2 = torch.load('x-file') # 载入

In [5]:
x2

tensor([0, 1, 2, 3])

In [6]:
y = torch.zeros(4)

In [7]:
torch.save([x,y], 'x-files')
x2,y2 = torch.load('x-files')

In [8]:
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [9]:
# 写入或读取从字符串映射到张量的字典
mydict = {"x":x, "y":y}
torch.save(mydict, 'mydict')
mydict2 =torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [15]:
# 加载和保存模型参数

class MLP(nn.Module):
    def __init__(self):
        super().__init__() # 调用父类，主要是初始化
        self.hidden = nn.Linear(20, 256) # linear 全连接层
        self.output = nn.Linear(256, 10)
    
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2,20))
net(X)

tensor([[-0.3017,  0.1840, -0.3865, -0.1925, -0.3965,  0.0090,  0.4229,  0.5486,
          0.0892, -0.1557],
        [-0.0207, -0.0732, -0.1023, -0.0252, -0.1413,  0.1359,  0.3047,  0.0293,
         -0.1148, -0.0616]], grad_fn=<AddmmBackward>)

In [16]:
torch.save(net.state_dict(), 'mlp.params') #存储

In [17]:
# 存的时候要把网络结构带走
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval() #这个啥意思？

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [19]:
Y = net(X)
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])